spring.application.name=fotofetch

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fotofetch_db
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=FotofetchSuperSecretKeyForJwtAuthentication2026VeryLongSecret
jwt.expiration=86400000